# Generated by Django 3.1.7 on 2021-03-22 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FILE', models.FileField(blank=True, null=True, upload_to='Assignments/')),
                ('description', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ManyToManyField(default='', to='database.Course')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted', models.BooleanField(default=False)),
                ('date', models.DateTimeField()),
                ('FILE', models.FileField(blank=True, null=True, upload_to='Submissions/')),
                ('remarks', models.TextField(default='None', max_length=255)),
                ('assignment', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.assignment')),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course', models.ManyToManyField(default='', to='database.Course')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=50)),
                ('Course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.course')),
                ('professor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.professor')),
            ],
        ),
        migrations.AddField(
            model_name='assignment',
            name='Classes',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='database.classes'),
        ),
    ]
