# Generated by Django 3.1.7 on 2021-04-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20210323_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='FILE',
            field=models.FileField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='FILE',
            field=models.FileField(blank=True, default='', null=True, upload_to='Submissions/'),
        ),
    ]
