# Generated by Django 3.1.7 on 2021-04-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_remove_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='FILE',
            field=models.FileField(blank=True, upload_to='Submissions/'),
        ),
    ]
